language: python
dist: xenial
sudo: false
python:
  - 3.7
matrix:
  include:
    - python: 3.7
      dist: trusty
      virtualenv:
        system_site_packages: true
      addons:
        apt:
          packages:
            - python-requests
            - python-coverage
            
addons:
  apt:
    packages:
      - python3-pip

before_install:
  - pip3 install -U pytest pytest-cov pylint numpy

script:
  - cd tests/ && pytest --cov kineticpy

after_success:
  - bash <(curl -s https://codecov.io/bash)

   
