dist: trusty

language: python

python:
    - '3.7'

addons:
  apt:
    packages:
      - python3-pip

before_install:
  - pip3 install -U pytest pytest-cov pylint numpy

script:
  - cd tests/ && pytest --cov kineticpy

after_success:
  - bash <(curl -s https://codecov.io/bash)